### ISSUE TITLE
CC just gives an NPE for this simple example

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-tool#109]
[exampleCC.zip](https://github.com/eMoflon/emoflon-tool/files/514177/exampleCC.zip)

**Comment by erhanleblebici** [comment]
this was due to the new ID mechanism and has been fixed.
Nevertheless, CC currently won't work without configuring your native library location as we use external DLLs. Please find a configured version of your projects attached.

[CC_Example.zip](https://github.com/eMoflon/emoflon-tool/files/515247/CC_Example.zip)
