### ISSUE TITLE
Review of plugin dependencies

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-tool#253]
Some new and unfortunate dependencies appear to have been introduced recently:

` Unresolved requirement: Require-Bundle: org.moflon.ide.core; bundle-version="2.1.0"
    -> Bundle-SymbolicName: org.moflon.ide.core; bundle-version="2.2.0.201704132021"; singleton:="true"
       org.moflon.ide.core [942]
         Unresolved requirement: Require-Bundle: org.moflon.gt.mosl.codeadapter; bundle-version="1.0.0"
           -> Bundle-SymbolicName: org.moflon.gt.mosl.codeadapter; bundle-version="1.0.0.201704132021"
              org.moflon.gt.mosl.codeadapter [941]`

Please check and see if these are really necessary.

**Comment by RolandKluge** [comment]
In fact, these dependencies should (in principle) not be there.

The reason is that, currently, the MOSLGTBuilder (https://github.com/eMoflon/emoflon-tool/blob/master/org.moflon.ide.core/src/org/moflon/ide/core/runtime/builders/MOSLGTBuilder.java) resides in this project.

@SaschaEdwinZander Can you try to migrate the builder away?
